name: my_notes
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.6
  table_calendar: ^3.0.7
  flutter_local_notifications: ^17.2.2
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  device_info_plus: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

#flutter_icons:
  #android: true
  #ios: true
  #image_path: "assets/notepad.png"
  #adaptive_icon_foreground: "assets/notepad.png"
  #adaptive_icon_background: "#FFFFFF"
  #remove_alpha_ios: true  # Added to remove alpha channel for iOS

flutter:
  uses-material-design: true
