// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaHV-PAXgYcv9J9ESuLN_AGGeLUHmrAVU',
    appId: '1:343699501183:web:4effaf8a7fdad74b414f4a',
    messagingSenderId: '343699501183',
    projectId: 'my-notes-ya',
    authDomain: 'my-notes-ya.firebaseapp.com',
    storageBucket: 'my-notes-ya.appspot.com',
    measurementId: 'G-1HQCZTRM74',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNNl6nE9yu_DZIFXvfBQ7rHfwHqy-Wr0U',
    appId: '1:343699501183:android:30ad808bc54c5f90414f4a',
    messagingSenderId: '343699501183',
    projectId: 'my-notes-ya',
    storageBucket: 'my-notes-ya.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAa4h--G5_XgA1aws5j5yHUqRBdU2TIlYQ',
    appId: '1:343699501183:ios:64163ea91110845c414f4a',
    messagingSenderId: '343699501183',
    projectId: 'my-notes-ya',
    storageBucket: 'my-notes-ya.appspot.com',
    iosBundleId: 'com.example.myNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAa4h--G5_XgA1aws5j5yHUqRBdU2TIlYQ',
    appId: '1:343699501183:ios:64163ea91110845c414f4a',
    messagingSenderId: '343699501183',
    projectId: 'my-notes-ya',
    storageBucket: 'my-notes-ya.appspot.com',
    iosBundleId: 'com.example.myNotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaHV-PAXgYcv9J9ESuLN_AGGeLUHmrAVU',
    appId: '1:343699501183:web:100a9dd10e966bf5414f4a',
    messagingSenderId: '343699501183',
    projectId: 'my-notes-ya',
    authDomain: 'my-notes-ya.firebaseapp.com',
    storageBucket: 'my-notes-ya.appspot.com',
    measurementId: 'G-LV341Z07N1',
  );
}
